apiVersion: apps/v1
kind: Deployment
metadata:
  name: solicitudes
spec:
  replicas: 1 #cantidad de pods que se van a crear
  selector:
    matchLabels:
      app: solicitudes #el deployment cuida a los pods con esta etiqueta
  template: #plantilla de los pods que se van a crear
    metadata:
      labels:
        app: solicitudes #enruta a los pods con esta etiqueta (debe calzar con el selector del service)
    spec:
      containers:
        - name: arka-lite-servicio-solicitud-1
          image: arka-lite-servicio-solicitud #traefik/whoami #imagen de Docker que se construye en el workflow de CI
          imagePullPolicy: IfNotPresent #no descarga la imagen si ya está en el nodo
          ports:
            - containerPort: 8080
          env:
            - name: NOTIFICATION_URL
              value: http://servicio-notificador:8080/notificaciones # URL del servicio de notificaciones
---
apiVersion: v1
kind: Service
metadata:
  name: solicitudes
spec:
  type: NodePort
  selector:
    app: solicitudes #enruta a los pods con esta etiqueta (debe calzar con el deployment)
  ports:
    - port: 8080
      targetPort: 8080