spring.application.name=servicio-solicitudes

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/arka}
spring.datasource.username=${DB_USER:arka}
spring.datasource.password=${DB_PASSWORD:arka}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always

notificaciones.url=${NOTIFICACIONES_URL:http://localhost:8081/eventos/solicitud-enviada}
